import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { aeadDecrypt } from '../src/primitives/aead.js';

/**
 * Wycheproof AES-GCM vectors (C2SP/wycheproof, filtered to
 * keySize=256/ivSize=96/tagSize=128 — the only shape this package
 * supports). Covers adversarial edge cases the NIST/McGrew-Viega
 * vectors in `aead-aes-gcm-kats.test.ts` do not: short tags, malformed
 * tags, tag collision cases, counter wrap (J0 at boundary), etc.
 *
 * File was generated by filtering
 *   https://github.com/C2SP/wycheproof/blob/main/testvectors_v1/aes_gcm_test.json
 * — the snapshot under `test/vectors/aead/wycheproof-aes-256-gcm.json`
 * preserves group metadata so the filter is self-describing.
 *
 * Wycheproof result codes:
 * - `"valid"`     — decrypt must succeed and plaintext must match.
 * - `"invalid"`   — decrypt must throw (forgery / tamper / wrong key).
 * - `"acceptable"` — vector is at the edge of a known weakness; a
 *   compliant implementation may or may not reject. We treat both
 *   outcomes as passing but assert plaintext equality on success.
 */

interface WycheproofTest {
  tcId: number;
  comment: string;
  flags: readonly string[];
  key: string;
  iv: string;
  aad: string;
  msg: string;
  ct: string;
  tag: string;
  result: 'valid' | 'invalid' | 'acceptable';
}

interface WycheproofGroup {
  keySize: number;
  ivSize: number;
  tagSize: number;
  type: string;
  tests: readonly WycheproofTest[];
}

interface WycheproofVectors {
  algorithm: string;
  numberOfTests: number;
  testGroups: readonly WycheproofGroup[];
}

const fromHex = (s: string): Uint8Array => Buffer.from(s, 'hex');

const VECTORS_PATH = fileURLToPath(
  new URL('./vectors/aead/wycheproof-aes-256-gcm.json', import.meta.url),
);
const vectors = JSON.parse(readFileSync(VECTORS_PATH, 'utf8')) as WycheproofVectors;

describe(`Wycheproof AES-256-GCM (${vectors.numberOfTests} vectors)`, () => {
  for (const group of vectors.testGroups) {
    for (const t of group.tests) {
      const label = `tcId=${t.tcId} ${t.result}${t.comment ? ` — ${t.comment}` : ''}`;

      it(label, () => {
        const key = fromHex(t.key);
        const iv = fromHex(t.iv);
        const ciphertext = fromHex(t.ct);
        const tag = fromHex(t.tag);
        const aad = fromHex(t.aad);
        const expectedPlaintext = fromHex(t.msg);

        if (t.result === 'valid') {
          const recovered = aeadDecrypt('AES-256-GCM', key, iv, ciphertext, tag, aad);
          expect(Buffer.from(recovered).toString('hex')).toBe(t.msg);
        } else if (t.result === 'invalid') {
          expect(() => aeadDecrypt('AES-256-GCM', key, iv, ciphertext, tag, aad)).toThrow();
        } else {
          // acceptable — either outcome is OK; if it decrypts, plaintext must match.
          try {
            const recovered = aeadDecrypt('AES-256-GCM', key, iv, ciphertext, tag, aad);
            expect(Buffer.from(recovered).toString('hex')).toBe(
              Buffer.from(expectedPlaintext).toString('hex'),
            );
          } catch {
            // Acceptable failure path — no assertion needed.
          }
        }
      });
    }
  }
});
